### ISSUE TITLE
Add `publisher` for `article` types

### ISSUE THREAD

**Issue by banesullivan** [citation-file-format/ruby-cff#104]
It appears that the `publisher` field is not used with the `article` type. For instance, here is a `.cff` from https://github.com/pyvista/pyvista/pull/2218

```yml
cff-version: 1.2.0
message: "If you use this software, please cite it as below."
preferred-citation:
  type: article
  authors:
  - family-names: "Sullivan"
    given-names: "Bane"
    orcid: "https://orcid.org/0000-0001-8628-4566"
  - family-names: "Kaszynski"
    given-names: "Alexander"
    orcid: "https://orcid.org/0000-0002-8232-7212"
  doi: "10.21105/joss.01450"
  journal: "Journal of Open Source Software"
  publisher: 
    name: "The Open Journal"
  month: May
  title: "PyVista: 3D plotting and mesh analysis through a streamlined interface for the Visualization Toolkit (VTK)"
  volume: 4
  issue: 37
  start: 1450
  year: 2019
  url: "https://github.com/pyvista/pyvista"
```

This renders the BibTex as

```bib
@article{Sullivan_PyVista_3D_plotting_2019,
  author = {Sullivan, Bane and Kaszynski, Alexander},
  doi = {10.21105/joss.01450},
  journal = {Journal of Open Source Software},
  month = {May},
  number = {37},
  pages = {1450},
  title = {{PyVista: 3D plotting and mesh analysis through a streamlined interface for the Visualization Toolkit (VTK)}},
  url = {https://github.com/pyvista/pyvista},
  volume = {4},
  year = {2019}
}
```

But we expect:

```bib
@article{sullivan2019pyvista,
  author = {Bane Sullivan and Alexander Kaszynski},
  doi = {10.21105/joss.01450},
  journal = {Journal of Open Source Software},
  month = {May},
  number = {37},
  pages = {1450},
  title = {{PyVista}: {3D} plotting and mesh analysis through a streamlined interface for the {Visualization Toolkit} ({VTK})},
  url = {https://doi.org/10.21105/joss.01450},
  volume = {4},
  year = {2019},
  publisher = {The Open Journal}
}
```

The only difference (besides name formatting and URL as expected) is that the `publisher` field was not included in the generated BibTex from the `.cff` file
