### ISSUE TITLE
"references" erroneously requires many optional fields

### ISSUE THREAD

**Issue by mr-c** [citation-file-format/ruby-cff#52]
all of 'authors', 'contact', 'editors', 'editors-series', 'recipients', 'senders', and  'translators' seems to be required by the code, yet only `authors` is [required](https://github.com/citation-file-format/ruby-cff/blob/1fa0fdf680dc67477e3e024dd66535dab2bc5aca/lib/schema/1.2.0.json#L1587) by the spec

The following minimized example fails validation:

``` yaml
cff-version: "1.1.0"
message: |
  To reference the CWL project in scholarly work, please cite the following work.
  To reference a particular version of the CWL standards, please see the entries
  under "references"
title: "Methods Included: Standardizing Computational Reuse and Portability with the Common Workflow Language"
identifiers: 
  - type: url
    value: "https://arxiv.org/abs/2105.07028"
authors: 
  - given-names: "Michael R."
    family-names: Crusoe
    affiliation: "VU Amsterdam, Department of Computer Science; Software Freedom Conservancy, Common Workflow Language project"
    orcid: "https://orcid.org/0000-0002-2961-9670"
references
  - type: standard
    title: "Common Workflow Language, v1.0"
    authors:
     - given-names: Peter
       family-names: Amstutz
       orcid: "https://orcid.org/0000-0003-3566-7705"
       affiliation: "Arvados Project, Veritas Genetics"
```

```Traceback (most recent call last):
	14: from test.rb:3:in `<main>'
	13: from /home/michael/.gem/ruby/2.7.0/gems/cff-0.6.0/lib/cff/file.rb:116:in `validate!'
	12: from /home/michael/.gem/ruby/2.7.0/gems/cff-0.6.0/lib/cff/file.rb:162:in `method_missing'
	11: from /home/michael/.gem/ruby/2.7.0/gems/cff-0.6.0/lib/cff/validatable.rb:32:in `validate!'
	10: from /home/michael/.gem/ruby/2.7.0/gems/cff-0.6.0/lib/cff/validatable.rb:47:in `validate'
	 9: from /home/michael/.gem/ruby/2.7.0/gems/cff-0.6.0/lib/cff/model.rb:121:in `fields'
	 8: from /home/michael/.gem/ruby/2.7.0/gems/cff-0.6.0/lib/cff/util.rb:55:in `fields_to_hash'
	 7: from /home/michael/.gem/ruby/2.7.0/gems/cff-0.6.0/lib/cff/util.rb:55:in `each'
	 6: from /home/michael/.gem/ruby/2.7.0/gems/cff-0.6.0/lib/cff/util.rb:58:in `block in fields_to_hash'
	 5: from /home/michael/.gem/ruby/2.7.0/gems/cff-0.6.0/lib/cff/util.rb:58:in `map'
	 4: from /home/michael/.gem/ruby/2.7.0/gems/cff-0.6.0/lib/cff/util.rb:59:in `block (2 levels) in fields_to_hash'
	 3: from /home/michael/.gem/ruby/2.7.0/gems/cff-0.6.0/lib/cff/reference.rb:285:in `fields'
	 2: from /home/michael/.gem/ruby/2.7.0/gems/cff-0.6.0/lib/cff/reference.rb:285:in `each'
	 1: from /home/michael/.gem/ruby/2.7.0/gems/cff-0.6.0/lib/cff/reference.rb:286:in `block in fields'
/home/michael/.gem/ruby/2.7.0/gems/cff-0.6.0/lib/cff/util.rb:49:in `normalize_modelpart_array!': undefined method `select!' for nil:NilClass (NoMethodError)
```

The following passes validation by adding extra fields to the `references`:
``` yaml
cff-version: "1.1.0"
message: |
  To reference the CWL project in scholarly work, please cite the following work.
  To reference a particular version of the CWL standards, please see the entries
  under "references"
title: "Methods Included: Standardizing Computational Reuse and Portability with the Common Workflow Language"
identifiers: 
  - type: url
    value: "https://arxiv.org/abs/2105.07028"
authors: 
  - given-names: "Michael R."
    orcid: "https://orcid.org/0000-0002-2961-9670"
references:
  - type: standard
    title: "Common Workflow Language, v1.0"
    authors:
     - given-names: Peter
       family-names: Amstutz
       orcid: "https://orcid.org/0000-0003-3566-7705"
    contact:
     - given-names: "Michael R."
       family-names: Crusoe
       orcid: "https://orcid.org/0000-0002-2961-9670"
    editors:
     - given-names: "Michael R."
       family-names: Crusoe
       orcid: "https://orcid.org/0000-0002-2961-9670"
    editors-series:
     - given-names: "Michael R."
       family-names: Crusoe
       orcid: "https://orcid.org/0000-0002-2961-9670"
    recipients:
     - given-names: "Michael R."
       family-names: Crusoe
       orcid: "https://orcid.org/0000-0002-2961-9670"
    senders:
     - given-names: "Michael R."
       family-names: Crusoe
       orcid: "https://orcid.org/0000-0002-2961-9670"
    translators:
     - given-names: "Michael R."
       family-names: Crusoe
       orcid: "https://orcid.org/0000-0002-2961-9670"
```
