### ISSUE TITLE
bibtex full name from name parts and capitalisation

### ISSUE THREAD

**Issue by tvercaut** [citation-file-format/ruby-cff#63]
Apologies if this was initially posted at https://github.com/citation-file-format/cff-converter-python/issues/156
I wrongly thought that GitHub was using the python converter under the hood rather than this ruby code. The same problem occurs here though and a fix is probably good in both repos.

I am looking into using cff files from some github repos and stumbled onto some issues. The current version is here:
https://github.com/Project-MONAI/MONAI/blob/dev/CITATION.cff

It generates the following bibtex:
```bibtex
@misc{MONAI_Consortium_MONAI_Medical_Open_2020,
author = {MONAI Consortium},
doi = {10.5281/zenodo.4323058},
month = {3},
title = {MONAI: Medical Open Network for AI},
url = {https://github.com/Project-MONAI/MONAI},
year = {2020}
}
```
which means bibtex can transforms the author name to "M. Consortium"

I tried modifying the CFF file to use an [entity](https://github.com/citation-file-format/citation-file-format/blob/main/README.md#entity-objects) rather than a [person](https://github.com/citation-file-format/citation-file-format/blob/main/README.md#person-objects) as an author, which seems authorised by the [standard](https://github.com/citation-file-format/citation-file-format/blob/main/README.md#software-citation-metadata-required)
```yaml
# YAML 1.2
# Metadata for citation of this software according to the CFF format (https://citation-file-format.github.io/)
#
---
title: "MONAI: Medical Open Network for AI"
abstract: "AI Toolkit for Healthcare Imaging"
authors:
  - name: "MONAI Consortium"
date-released: 2020-03-28
version: "0.6.0"
doi: "10.5281/zenodo.4323058"
license: "Apache-2.0"
repository-code: "https://github.com/Project-MONAI/MONAI"
cff-version: "1.1.0"
message: "If you use this software, please cite it using these metadata."
```
but this led to the author information being dropped in the bibtex output (at least using the python converter):
```bibtex
@misc{YourReferenceHere,
author = {},
doi = {10.5281/zenodo.4323058},
month = {3},
title = {MONAI: Medical Open Network for AI},
url = {https://github.com/Project-MONAI/MONAI},
year = {2020}
}
```

Also, is there a way to force the bibtex output to preserve some capitalisation (MONAI in the above)?
From the [bibtex manual](http://mirrors.ctan.org/info/bibtex/tamethebeast/ttb_en.pdf), it would already be nicer to use a format along the lines of:
```
von Last, Jr, First
```
or maybe even better use curly brackets whenever the namepart includes a space:
```
{von Last}, Jr, First
```
so that if the `Jr` or `First` part is empty we get `{von Last}`.

Something along the lines of this python snippet would probably work:
```python
fullname = ', '.join(['{'+namepart+'}' if (' ' in namepart) else namepart for namepart in nps if namepart is not None])
```
