### ISSUE TITLE
Parsing / validation issue

### ISSUE THREAD

**Issue by floehopper** [citation-file-format/ruby-cff#65]
We've just tried adding [this `CITATION.cff` file](https://github.com/luox-app/luox/blob/e1520a2907cc0ccd5d0aba520eda84b4fde6243f/CITATION.cff) to our repo. See content below:

```yaml
cff-version: 1.1.0
message: "If you use this software repository, please cite it using these metadata. If you have used luox for calculations, please cite our article in Wellcome Open Research (https://doi.org/10.12688/wellcomeopenres.16595.2)."
authors:
  - family-names: Spitschan
    given-names: Manuel
    orcid: https://orcid.org/0000-0003-4925-7248
title: "luox: Platform for calculating quantities related to light and lighting"
```

However, GitHub is displaying the following error message:

> Your **CITATION.cff** file cannot be parsed. Make sure the formatting is correct.

I've run the following code against the latest version of the gem (8676ecbcd724908dc447a02163cc2f79ac2de5f9):

```ruby
cff = CFF::File.read('CITATION.cff')

p cff # => #<CFF::File:0x00007f89a72bba50 @filename="CITATION.cff", @model=#<CFF::Model:0x00007f89a72bba28 @fields={"cff-version"=>"1.2.0", "message"=>"If you use this software repository, please cite it using these metadata. If you have used luox for calculations, please cite our article in Wellcome Open Research (https://doi.org/10.12688/wellcomeopenres.16595.2).", "authors"=>[#<CFF::Person:0x00007f89a72bb9d8 @fields={"family-names"=>"Spitschan", "given-names"=>"Manuel", "orcid"=>"https://orcid.org/0000-0003-4925-7248"}>], "title"=>"luox: Platform for calculating quantities related to light and lighting", "contact"=>[], "identifiers"=>[], "keywords"=>[], "references"=>[]}>, @comment=[], @dirty=false>

p cff.validate # => [true, []]
```
 i.e. it appears as if this passes validation.

Does anyone have any idea why GitHub might be rejecting the file?

I don't know if it's significant, but the `CFF::Model` instance seems to have the "cff-version" set to "1.2.0" whereas the `CITATION.cff` file has it set to "1.1.0".

Or might it be because there is [a `CITATION` file](https://github.com/luox-app/luox/blob/e1520a2907cc0ccd5d0aba520eda84b4fde6243f/CITATION) in the repo as well as `CITATION.cff`...?
