### ISSUE TITLE
Feature Request: Ability to cite a published article 

### ISSUE THREAD

**Issue by ddsjoberg** [citation-file-format/ruby-cff#70]
Hello! I have a GitHub repository that has an associated publication. I tried to create a `CITATION.cff` file that would produce the proper citation of the manuscript, but I could not get it. Is there a way to have more control over the resulting citations that now appear on the GitHub site? If not, can something like this be implemented?

For example, here is my `CITATION.cff` file.
```
cff-version: 1.2.0
message: "To cite gtsummary in publications use:"
type: article
authors:
- family-names: "Sjoberg"
  given-names: "Daniel D."
  orcid: "https://orcid.org/0000-0003-0862-2018"
  website: "https://www.danieldsjoberg.com/"
- family-names: "Whiting"
  given-names: "Karissa"
  orcid: "https://orcid.org/0000-0002-4683-1868"
- family-names: "Curry"
  given-names: "Michael"
  orcid: "https://orcid.org/0000-0002-0261-4044"
- family-names: "Lavery"
  given-names: "Jessica A."
  orcid: "https://orcid.org/0000-0002-2746-5647"
- family-names: "Larmarange"
  given-names: "Joseph"
  orcid: "https://orcid.org/0000-0001-7097-700X"
title: "Reproducible Summary Tables with the gtsummary Package"
journal: "The R Journal"
year: 2021
volume: 13
issue: 1
start: 570
end: 580
doi: 10.32614/RJ-2021-053
url: "https://doi.org/10.32614/RJ-2021-053"
repository: "https://github.com/ddsjoberg/gtsummary"
```

This is the proper BibTex entry for the publication:
```
@Article{gtsummary,
  author = {Daniel D. Sjoberg and Karissa Whiting and Michael Curry and Jessica A. Lavery and Joseph Larmarange},
  title = {Reproducible Summary Tables with the gtsummary Package},
  journal = {{The R Journal}},
  year = {2021},
  url = {https://doi.org/10.32614/RJ-2021-053},
  doi = {10.32614/RJ-2021-053},
  volume = {13},
  issue = {1},
  pages = {570-580},
}
```

Below is what renders on the repository's GitHub site. There is no reference to the journal or the issue number, and the entry is misc instead of an article.

```
@misc{Sjoberg_Reproducible_Summary_Tables,
  author = {Sjoberg, Daniel D. and Whiting, Karissa and Curry, Michael and Lavery, Jessica A. and Larmarange, Joseph},
  doi = {10.32614/RJ-2021-053},
  title = {Reproducible Summary Tables with the gtsummary Package},
  url = {https://doi.org/10.32614/RJ-2021-053}
}
```

There are similar issues when the citation is converted to APA format. Happy to provide more details if helpful!  Thank you!
