### ISSUE TITLE
implement preferred-citation to a book

### ISSUE THREAD

**Issue by bueler** [citation-file-format/ruby-cff#77]
My repo https://github.com/bueler/p4pdes supports a book. (Very old fashioned, I know.)  I would like users of the software to cite the book.  So the preferred-citation mechanism seems good.  But it produces an incomplete book citation.  In particular, my attempt below produced an APA and bibtex citation which did not have the publisher or address.  Ideally there would be an ISBN too.  (So I reverted to having `CITATION.bib` in the repo, which is the way the `master` branch looks now.)

Is a CFF extension needed?  If so, where should the issue go?

Thanks!

```
cff-version: 1.2.0
message: "If you use this software, please cite my book below."
authors:
- family-names: "Bueler"
  given-names: "Ed"
title: "PETSc for Partial Differential Equations: Numerical Solutions in C and Python"
date-released: 2021
url: "https://github.com/bueler/p4pdes"
preferred-citation:
  type: book
  authors:
  - family-names: "Bueler"
    given-names: "Ed"
  title: "PETSc for Partial Differential Equations: Numerical Solutions in C and Python"
  publisher: SIAM Press
  address: Philadelphia
  url: "https://github.com/bueler/p4pdes"
  isbn: 9781611976304
  year: 2021
```
