### ISSUE TITLE
Removing month also removes year from the output of article

### ISSUE THREAD

**Issue by h4iku** [citation-file-format/ruby-cff#78]
Removing `month` from the `preferred-citation` part for `@article` removes `year` from the output as well.

For example:

```yaml
cff-version: 1.2.0
message: "If you use this software, please cite it as below."
authors:
- family-names: "Lisa"
  given-names: "Mona"
title: "My Research Software"
preferred-citation:
  type: article
  authors:
  - family-names: "Lisa"
    given-names: "Mona"
  journal: "Journal Title"
  title: "My awesome research software"
  year: 2021
```

returns:

```bib
@article{Lisa_My_awesome_research,
author = {Lisa, Mona},
journal = {Journal Title},
title = {{My awesome research software}}
}
```
```
Lisa, M. My awesome research software. Journal Title
```

While adding `month` will also give you `year`:

```bib
@article{Lisa_My_awesome_research_2021,
author = {Lisa, Mona},
journal = {Journal Title},
month = {9},
title = {{My awesome research software}},
year = {2021}
}
```
```
Lisa, M. (2021). My awesome research software. Journal Title
```
