### ISSUE TITLE
`preferred-citation` for `conference-paper`

### ISSUE THREAD

**Issue by tgamblin** [citation-file-format/ruby-cff#79]
Hi! Thank for `CITATION.cff`. I'm attempting to get GitHub to display this citation properly in BibTeX and APA format:

```yaml
preferred-citation:
  type: conference-paper
  authors:
  - family-names: "Gamblin"
    given-names: "Todd"
  - family-names: "LeGendre"
    given-names: "Matthew"
  - family-names: "Collette"
    given-names: "Michael R."
  - family-names: "Lee"
    given-names: "Gregory L."
  - family-names: "Moody"
    given-names: "Adam"
  - family-names: "de Supinski"
    given-names: "Bronis R."
  - family-names: "Futral"
    given-names: "Scott"
  title: "The Spack Package Manager: Bringing Order to HPC Software Chaos"
  conference:
    name: "Supercomputing 2015 (SC’15)"
    date-start: 2015-11-15
    date-end: 2015-11-20
    city: "Austin"
    region: "Texas"
    country: "USA"
```

I would expect that to come out something like this (abbreviated initials would be fine):

> Todd Gamblin, Matthew P. LeGendre, Michael R. Collette, Gregory L. Lee, Adam Moody, Bronis R. de Supinski, and W. Scott Futral. The Spack Package Manager: Bringing Order to HPC Software Chaos. In Supercomputing 2015 (SC’15), Austin, Texas, November 15-20 2015.

and, in BibTeX:

```
@inproceedings{SomeKindOfKey,
	address = {Austin, Texas},
	author = {Todd Gamblin and Matthew P. LeGendre and Michael R. Collette and Gregory L. Lee and Adam Moody and Bronis R. de Supinski and W. Scott Futral},
	booktitle = {Supercomputing 2015 (SC'15)},
	month = {November 15-20},
	title = {{The Spack Package Manager: Bringing order to HPC software chaos}},
	year = {2015}}
```

But it seems like the only parts I get are:

> Gamblin, T., LeGendre, M., Collette, M. R., Lee, G. L., Moody, A., de Supinski, B. R., & Futral, S. The Spack Package Manager: Bringing Order to HPC Software Chaos

and:

```
@inproceedings{Gamblin_The_Spack_Package,
author = {Gamblin, Todd and LeGendre, Matthew and Collette, Michael R. and Lee, Gregory L. and Moody, Adam and de Supinski, Bronis R. and Futral, Scott},
title = {{The Spack Package Manager: Bringing Order to HPC Software Chaos}}
}
```

Am I missing something or is this just not supported yet?
